import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "../components/ThemeProvider";
import { SocketProvider } from "../context/SocketContext";
import { VideoCallProvider } from "../context/VideoCallContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <SocketProvider>
          <VideoCallProvider>
            <div className="flex-grow relative">
              {children}
            </div>
            <Footer />
          </VideoCallProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
